db = "pq"
cache = "./postgresql-cache"

[postgresql]
url = "user=egorcod dbname=viz sslmode=disable"
table = "records"
days-table = "records_days"
hours-table = "records_hours"
minutes-table = "records_minutes"
format = ["date", "number", "number", "number", "number", "number"]
